## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
  - 0.7
  - 1.0
notifications:
  email: false
git:
  depth: 99999999

# Integration with JuMP-dev gitter channel
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cb052648b833828852b4
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

after_success:
  - julia -e '(VERSION >= v"0.7" && using Pkg); cd(Pkg.dir("LinQuadOptInterface")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
